name: Tests against Latest Docker Moby

on:
  schedule:
    # nightly build, at 23:59 CEST
    - cron:  '59 23 * * *'

jobs:
  test_latest_moby:
    strategy:
      matrix:
        rootless-docker: [true, false]
    name: "Core tests using latest moby/moby"
    runs-on: 'ubuntu-latest'
    continue-on-error: true
    steps:
      - name: Set the Docker Install type
        run: |
          echo "docker_install_type=${{ matrix.rootless-docker == true && 'Rootless' || 'Rootful' }}" >> "$GITHUB_ENV"

      - name: Setup rootless Docker
        if: ${{ matrix.rootless-docker }}
        uses: ScribeMD/rootless-docker@6bd157a512c2fafa4e0243a8aa87d964eb890886  # v0.2.2

      - name: Remove Docker root socket
        if: ${{ matrix.rootless-docker }}
        run: sudo rm -rf /var/run/docker.sock

      - name: Check out code into the Go module directory
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Set up Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5
        with:
            go-version-file: 'go.mod'
            cache-dependency-path: 'go.sum'
        id: go

      - name: modVerify
        run: go mod verify

      - name: modTidy
        run: go mod tidy

      - name: Install Latest Docker
        run: curl https://get.docker.com | CHANNEL=test sh

      - name: go test
        timeout-minutes: 30
        run: make test-unit
